Practice task API testing
avsokolovskiy/reqres-api-tests pull request #1
Opened 2022-11-13 21:59 UTC by avsokolovskiy

Task: https://brainly.atlassian.net/wiki/spaces/QA/pages/1052312452/3.+API+testing#3.2.1.-API-testing-basics
Implemented: 
[+] Create automated API tests to cover endpoints from https://reqres.in/ resource

### Endpoints

#### Simple API tests
1  GET: https://reqres.in/api/users - LIST USERS
2 GET: https://reqres.in/api/users/2 - SINGLE USER
3 GET: https://reqres.in/api/users/23 - SINGLE USER NOT FOUND
4 POST: https://reqres.in/api/users  - CREATE
5 PUT: https://reqres.in/api/users/2 - UPDATE
6 DELETE: https://reqres.in/api/users/2 - DELETE
7 POST: https://reqres.in/api/register  - REGISTER - SUCCESSFUL
8 POST: https://reqres.in/api/register  - REGISTER - UNSUCCESSFUL
#### Performance API test. Check if endpoint response in less than 3 seconds
9 GET: https://reqres.in/api/users?delay=3 - DELAYED RESPONSE

2022-11-15 07:47 UTC, marcinoleksiak requested changes
not bad :)
a lot of comments but mainly cosmetics :)

*remember to add .idea files to the list of ignored files

2022-11-15 07:47 UTC, marcinoleksiak commented on bc_api_tests.py
> +
PUT actually creates a new object, and does a replacement. you actually don't have any information in this test about the object before its modification - like what was his name. It would be great to verify if the change actually happened

2022-11-15 07:47 UTC, marcinoleksiak commented on bc_api_tests.py
> +        self.assertEqual('', response.text)
In this test we also have a check for a response but not necessarily if the user was really deleted. In a real app, hardcoding ID here may lead to a single pass situation. on first run you delete the user and in the second there will be nothing to delete :)

2022-11-15 07:47 UTC, marcinoleksiak commented on bc_api_tests.py
> +    def test_post_user_signin(self) -> None:
I'd rename this test. `signin` means `login` and you use `register` endpoint here, not `login`
I'd also rename `user_json_login` and `resp_json` accordingly

2022-11-15 07:47 UTC, marcinoleksiak commented on bc_api_tests.py
> +        self.assertEqual(resp_json, response.json())
use dedicated assertion for comparing dictionaries

2022-11-15 07:47 UTC, marcinoleksiak commented on bc_api_tests.py
> +    def test_post_user_signin_negative(self) -> None:
the same as above: register, not login

2022-11-15 07:47 UTC, marcinoleksiak commented on bc_api_tests.py
> +            if json_set['email'] == '':
this `if` is tough in reading and understand. I'd like to suggest a bit different solution:
create sth like this:
```python
INVALID_REGISTRATIONS = [
    {
        "request_body": {"email": "", "password": ""},
        "error": "Missing email or username"
    }
]
```
and use in test:
```python
        for registration in INVALID_REGISTRATIONS:
            response = requests.post(f'{BASE_URL}/api/register/', json=registration["reuqest_body"],
                                     timeout=BASE_TIMEOUT)
```
it makes the code more friendly. reference to expected error is done the same way a fe lines after

2022-11-16 10:00 UTC, avsokolovskiy commented on bc_api_tests.py
> +                         response.headers['NEL'])
fixed

2022-11-16 10:14 UTC, avsokolovskiy commented on bc_api_tests.py
> +        self.assertEqual(1, response.json()['data'][0]['id'])
noted, fixed

2022-11-16 13:04 UTC, avsokolovskiy commented on bc_api_tests.py
> +        self.assertRegex(response.json()['data'][0]['email'],
implemented

2022-11-16 13:24 UTC, avsokolovskiy commented on bc_api_tests.py
> +        response = requests.get(f'{BASE_URL}/api/users/{USER_ID_BAD}', timeout=BASE_TIMEOUT)
fixed

2022-11-16 14:04 UTC, avsokolovskiy commented on bc_api_tests.py
> +        self.assertEqual('', response.text)
fixed

2022-11-16 14:21 UTC, avsokolovskiy commented on bc_api_tests.py
> +    def test_post_user_signin(self) -> None:
fixed

2022-11-16 14:22 UTC, avsokolovskiy commented on bc_api_tests.py
> +        self.assertEqual(resp_json, response.json())
fixed

2022-11-16 16:14 UTC, avsokolovskiy commented on bc_api_tests.py
> +            if json_set['email'] == '':
refactored

2022-11-17 16:42 UTC, marcinoleksiak approved these changes
Well done :)
Read my comments. Some cosmetic things left but lets move on.
Just remember about them in next chapters of this Bootcamp.
I'd like to focus more on the proper naming of variables/methods.

I'm not insisting on further changes in the 'update' test. A real app would not allow us to create the same user on and on probably. But lets leave it :)

Approved!

2022-11-17 20:59 UTC, avsokolovskiy commented on bc_api_tests.py
> +user_new_resp_json = {"id": 4, "token": "QpwL5tke4Pnpja7X4"}
fixed

2022-11-17 21:05 UTC, avsokolovskiy commented on Pipfile
> +jsonschema = "*"
i was playing with this lib :) and forgot to delete it from pip

2022-11-17 21:12 UTC, avsokolovskiy commented on bc_api_tests.py
> +        self.assertNotEqual(response_org.json()['job'], response_mod.json()['job'])
fixed

2022-11-17 21:12 UTC, merged